version: '3.8'

networks:
  banvic_network:
    driver: bridge

services:
  postgres_source:
    image: postgres:16
    container_name: banvic_source_db
    environment:
      - POSTGRES_DB=banvic
      - POSTGRES_USER=data_engineer
      - POSTGRES_PASSWORD=v3rysecur&pas5w0rd
    volumes:
      - ./source_data/banvic.sql:/docker-entrypoint-initdb.d/banvic.sql
    ports:
      - "55432:5432"
    networks:
      - banvic_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U data_engineer -d banvic" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_dw:
    image: postgres:16
    container_name: banvic_dw
    environment:
      - POSTGRES_DB=banvic_dw
      - POSTGRES_USER=dw_admin
      - POSTGRES_PASSWORD=dw_password
    ports:
      - "55433:5432"
    networks:
      - banvic_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dw_admin -d banvic_dw" ]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.9.2
    container_name: airflow_init
    depends_on:
      postgres_dw:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://dw_admin:dw_password@postgres_dw:5432/banvic_dw
      - AIRFLOW__WEBSERVER__SECRET_KEY=v3rysecur&airflowkey
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com
      "
    networks:
      - banvic_network

  airflow-scheduler:
    image: apache/airflow:2.9.2
    container_name: airflow_scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data_lake:/opt/airflow/data_lake
      - ./source_data:/opt/airflow/source_data
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://dw_admin:dw_password@postgres_dw:5432/banvic_dw
      - AIRFLOW__WEBSERVER__SECRET_KEY=v3rysecur&airflowkey
      - AIRFLOW_CONN_POSTGRES_SOURCE=postgres://data_engineer:v3rysecur&pas5w0rd@postgres_source:5432/banvic
      - AIRFLOW_CONN_POSTGRES_DW=postgres://dw_admin:dw_password@postgres_dw:5432/banvic_dw
    command: scheduler
    networks:
      - banvic_network

  airflow-webserver:
    image: apache/airflow:2.9.2
    container_name: airflow_webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data_lake:/opt/airflow/data_lake
      - ./souce_data:/opt/airflow/source_data
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://dw_admin:dw_password@postgres_dw:5432/banvic_dw
      - AIRFLOW__WEBSERVER__SECRET_KEY=v3rysecur&airflowkey
    command: webserver
    networks:
      - banvic_network
